// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5MZ8cSvYqUqKjXnmvgwXSyWShuXugalE',
    appId: '1:408491033836:web:3f5706803f2deb2ea951c9',
    messagingSenderId: '408491033836',
    projectId: 'musicshare-320d5',
    authDomain: 'musicshare-320d5.firebaseapp.com',
    databaseURL: 'https://musicshare-320d5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'musicshare-320d5.appspot.com',
    measurementId: 'G-95PF1PBN6W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCHofN7p32ul72Nu5FZrmU2r4paa1ftvI',
    appId: '1:408491033836:android:32c8a77758ff0ecba951c9',
    messagingSenderId: '408491033836',
    projectId: 'musicshare-320d5',
    databaseURL: 'https://musicshare-320d5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'musicshare-320d5.appspot.com',
  );
}
